name: Approve

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      target_environment:
        required: true
        type: string

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approved
        run: echo "test"
